; Listing generated by Microsoft (R) Optimizing Compiler Version 19.40.33808.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_MddBootstrapShutdown:PROC
EXTRN	__imp_MddBootstrapInitialize2:PROC
EXTRN	__imp_exit:PROC
PUBLIC	?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::Initialize
PUBLIC	?Options@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SA?AW4MddBootstrapInitializeOptions@@XZ ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::Options
PUBLIC	??1AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::~AutoInitialize
PUBLIC	??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::AutoInitialize
?g_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@3UAutoInitialize@12345@A DB 01H DUP (?) ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::g_autoInitialize
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ DD imagerel ??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ
	DD	imagerel ??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ+67
	DD	imagerel $unwind$??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ DD imagerel $LN6
	DD	imagerel $LN6+56
	DD	imagerel $unwind$?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ DD imagerel $LN9
	DD	imagerel $LN9+63
	DD	imagerel $unwind$??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ
pdata	ENDS
CRT$XCU	SEGMENT
?g_autoInitialize$initializer$@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@3P6AXXZEA DQ FLAT:??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::g_autoInitialize$initializer$
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ
_TEXT	SEGMENT
this$dead$ = 48
??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ PROC ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::AutoInitialize, COMDAT
; File C:\Local-Git\VChatGUI\SRC\VChat_WinUI3\packages\Microsoft.WindowsAppSDK.1.5.240428000\include\MddBootstrapAutoInitializer.cpp
; Line 29
$LN9:
	sub	rsp, 40					; 00000028H
; Line 73
	mov	r8, 1407656869641322496			; 13890077009c0000H
; Line 75
	lea	rdx, OFFSET FLAT:??_C@_11LOCGONAA@@
	mov	r9d, 8
	mov	ecx, 65541				; 00010005H
	call	QWORD PTR __imp_MddBootstrapInitialize2
; Line 76
	test	eax, eax
	jns	SHORT $LN4@AutoInitia
; Line 78
	mov	ecx, eax
	call	QWORD PTR __imp_exit
	int	3
$LN4@AutoInitia:
; Line 32
	lea	rax, OFFSET FLAT:?g_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@3UAutoInitialize@12345@A
	add	rsp, 40					; 00000028H
	ret	0
$LN7@AutoInitia:
??0AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ ENDP ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::AutoInitialize
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??1AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ PROC ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::~AutoInitialize, COMDAT
; File C:\Local-Git\VChatGUI\SRC\VChat_WinUI3\packages\Microsoft.WindowsAppSDK.1.5.240428000\include\MddBootstrapAutoInitializer.cpp
; Line 36
	rex_jmp	QWORD PTR __imp_MddBootstrapShutdown
??1AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@QEAA@XZ ENDP ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::~AutoInitialize
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Options@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SA?AW4MddBootstrapInitializeOptions@@XZ
_TEXT	SEGMENT
?Options@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SA?AW4MddBootstrapInitializeOptions@@XZ PROC ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::Options, COMDAT
; File C:\Local-Git\VChatGUI\SRC\VChat_WinUI3\packages\Microsoft.WindowsAppSDK.1.5.240428000\include\MddBootstrapAutoInitializer.cpp
; Line 43
	mov	eax, 8
; Line 67
	ret	0
?Options@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SA?AW4MddBootstrapInitializeOptions@@XZ ENDP ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::Options
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ
_TEXT	SEGMENT
?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ PROC ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::Initialize, COMDAT
; File C:\Local-Git\VChatGUI\SRC\VChat_WinUI3\packages\Microsoft.WindowsAppSDK.1.5.240428000\include\MddBootstrapAutoInitializer.cpp
; Line 70
$LN6:
	sub	rsp, 40					; 00000028H
; Line 73
	mov	r8, 1407656869641322496			; 13890077009c0000H
; Line 75
	lea	rdx, OFFSET FLAT:??_C@_11LOCGONAA@@
	mov	r9d, 8
	mov	ecx, 65541				; 00010005H
	call	QWORD PTR __imp_MddBootstrapInitialize2
; Line 76
	test	eax, eax
	jns	SHORT $LN2@Initialize
; Line 78
	mov	ecx, eax
	call	QWORD PTR __imp_exit
	int	3
$LN2@Initialize:
; Line 80
	add	rsp, 40					; 00000028H
	ret	0
$LN4@Initialize:
?Initialize@AutoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@SAXXZ ENDP ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::AutoInitialize::Initialize
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ
text$di	SEGMENT
??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ PROC ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::`dynamic initializer for 'g_autoInitialize'', COMDAT
; File C:\Local-Git\VChatGUI\SRC\VChat_WinUI3\packages\Microsoft.WindowsAppSDK.1.5.240428000\include\MddBootstrapAutoInitializer.cpp
; Line 82
	sub	rsp, 40					; 00000028H
; Line 73
	mov	r8, 1407656869641322496			; 13890077009c0000H
; Line 75
	lea	rdx, OFFSET FLAT:??_C@_11LOCGONAA@@
	mov	r9d, 8
	mov	ecx, 65541				; 00010005H
	call	QWORD PTR __imp_MddBootstrapInitialize2
; Line 76
	test	eax, eax
	jns	SHORT $LN6@dynamic
; Line 78
	mov	ecx, eax
	call	QWORD PTR __imp_exit
	int	3
$LN6@dynamic:
; Line 82
	lea	rcx, OFFSET FLAT:??__Fg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::`dynamic atexit destructor for 'g_autoInitialize''
	add	rsp, 40					; 00000028H
	jmp	atexit
$LN10@dynamic:
??__Eg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ ENDP ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::`dynamic initializer for 'g_autoInitialize''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Fg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ
text$yd	SEGMENT
??__Fg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ PROC ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::`dynamic atexit destructor for 'g_autoInitialize'', COMDAT
; File C:\Local-Git\VChatGUI\SRC\VChat_WinUI3\packages\Microsoft.WindowsAppSDK.1.5.240428000\include\MddBootstrapAutoInitializer.cpp
; Line 36
	rex_jmp	QWORD PTR __imp_MddBootstrapShutdown
??__Fg_autoInitialize@Bootstrap@DynamicDependency@ApplicationModel@Windows@Microsoft@@YAXXZ ENDP ; Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::`dynamic atexit destructor for 'g_autoInitialize''
text$yd	ENDS
END
