
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::VChat_WinUI3::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::VChat_WinUI3::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock greetingOutput()
        {
            return _greetingOutput;
        }
        void greetingOutput(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _greetingOutput = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button Start_Button()
        {
            return _Start_Button;
        }
        void Start_Button(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _Start_Button = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button Stop_Button()
        {
            return _Stop_Button;
        }
        void Stop_Button(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _Stop_Button = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer ScrollViewerVChat()
        {
            return _ScrollViewerVChat;
        }
        void ScrollViewerVChat(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _ScrollViewerVChat = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox VChatOutput()
        {
            return _VChatOutput;
        }
        void VChatOutput(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _VChatOutput = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _greetingOutput{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _Start_Button{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _Stop_Button{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _ScrollViewerVChat{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _VChatOutput{nullptr};
    };
}

