// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_VChat_WinUI3_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::VChat_WinUI3::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::VChat_WinUI3
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<VChat_WinUI3::implementation::XamlMetaDataProvider>())
    {
    }
}
