// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_VChat_WinUI3_0_H
#define WINRT_VChat_WinUI3_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::VChat_WinUI3
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::VChat_WinUI3::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::VChat_WinUI3::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::VChat_WinUI3::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::VChat_WinUI3::MainWindow> = L"VChat_WinUI3.MainWindow";
    template <> inline constexpr auto& name_v<winrt::VChat_WinUI3::XamlMetaDataProvider> = L"VChat_WinUI3.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::VChat_WinUI3::IMainWindow> = L"VChat_WinUI3.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::VChat_WinUI3::IMainWindow>{ 0xB72EDFF5,0x8210,0x5B37,{ 0xBD,0x48,0xBB,0x2A,0x12,0x54,0x50,0xF8 } }; // B72EDFF5-8210-5B37-BD48-BB2A125450F8
    template <> struct default_interface<winrt::VChat_WinUI3::MainWindow>{ using type = winrt::VChat_WinUI3::IMainWindow; };
    template <> struct default_interface<winrt::VChat_WinUI3::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::VChat_WinUI3::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_VChat_WinUI3_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::VChat_WinUI3::IMainWindow>
    {
        template <typename D> using type = consume_VChat_WinUI3_IMainWindow<D>;
    };
}
#endif
